# -*- coding: utf-8 -*-
"""reto 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19SkcXwcxNlZrqDG3brMPu5ZitKOCWBuS
"""

i = 1
x = 1
conta = 1
vacunas  = []
contador = []
letras_vacunas = []
a = ""

letras = input("ingrese la lista de vacunas: ")

for i in letras:
    if i != " ":
        vacunas.append(i)

for v in vacunas:   
       if x <= len(vacunas)-1:
            if v == vacunas[x]:            
                conta += 1
                x += 1
            else:
                letras_vacunas.append(v)
                contador.append(conta)
                conta = 1
                x += 1
if len(vacunas)-1 == len(vacunas)-2:
    conta += 1
    x += 1
else:
    letras_vacunas.append(v)
    contador.append(conta)
    conta = 1
    x += 1   
        
for c in letras_vacunas:   
    print(c , end = " ")
print("\n")
for c in contador:
    print(c, end = " ")