# -*- coding: utf-8 -*-
"""reto 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1As7xaoIyNpDyy6FVBcIhdBprX7VEfEY8
"""

nivel_de_riesgo = ""
personas_contagiadas_cepa_base = 0
cepa_reino_unido = 0
cepa_brasileña = 0

def tipo_de_riesgo(nivel_de_riesgo):  
  if cepa_brasileña >= 0 and cepa_brasileña <= 20:   
      nivel_de_riesgo = "uno"
  elif cepa_brasileña >= 21 and cepa_brasileña <= 30:
      nivel_de_riesgo = "dos"
  elif cepa_brasileña >= 31 and cepa_brasileña <= 50:
    nivel_de_riesgo = "tres"
  elif cepa_brasileña > 50:
      nivel_de_riesgo = "cuatro"
  return nivel_de_riesgo
  

personas_contagiadas_cepa_base = int(input("cantidad de contagiados de la cepa base: "))
cepa_reino_unido = personas_contagiadas_cepa_base * 2 + 4
cepa_brasileña =  int(personas_contagiadas_cepa_base + cepa_reino_unido) // 5

nivel_de_riesgo = tipo_de_riesgo(nivel_de_riesgo)
print(personas_contagiadas_cepa_base, cepa_reino_unido, cepa_brasileña)

print(nivel_de_riesgo)